name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.1.0)'
        required: true
        type: string
      prerelease:
        description: 'Mark as pre-release'
        required: false
        type: boolean
        default: false
      draft:
        description: 'Create as draft'
        required: false
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate version format
        run: |
          VERSION="${{ inputs.version }}"
          if ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Invalid version format. Use semantic versioning (e.g., 1.1.0)"
            exit 1
          fi
          echo "✓ Version format valid: $VERSION"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Update versions
        run: |
          VERSION="${{ inputs.version }}"
          
          # Update package.json
          npm version $VERSION --no-git-tag-version
          
          # Update manifest.json and versions.json
          npm run version
          
          echo "✓ Versions updated to $VERSION"

      - name: Run tests
        run: npm test

      - name: Build plugin
        run: npm run build

      - name: Verify build artifacts
        run: |
          for file in main.js manifest.json styles.css; do
            if [ ! -f "$file" ]; then
              echo "Error: Required file $file not found"
              exit 1
            fi
          done
          echo "✓ All required files present"
          ls -lh main.js manifest.json styles.css

      - name: Generate release notes
        id: release_notes
        run: |
          VERSION="${{ inputs.version }}"
          
          cat > release_notes.md << 'EOF'
          ## Manual Release v$VERSION
          
          This release was created manually via GitHub Actions.
          
          ### Installation
          
          Download `main.js`, `manifest.json`, and `styles.css` from the assets below.
          
          Place them in: `.obsidian/plugins/letterboxd-sync/`
          
          ### Notes
          
          Please refer to the [README](https://github.com/${{ github.repository }}/blob/main/README.md) for full documentation.
          EOF
          
          sed -i "s/\$VERSION/$VERSION/g" release_notes.md

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.version }}
          name: Release ${{ inputs.version }}
          body_path: release_notes.md
          draft: ${{ inputs.draft }}
          prerelease: ${{ inputs.prerelease }}
          files: |
            main.js
            manifest.json
            styles.css
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit version changes
        if: ${{ !inputs.draft }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json manifest.json versions.json
          git commit -m "Release v${{ inputs.version }}"
          git push origin main
